---
abstract: 'xxHash Implementation For Perl'
author:
  - 'Sanko Robinson C<< <sanko@cpan.org> >>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.19
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132510'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-xxHash
provides:
  Digest::xxHash:
    file: lib/Digest/xxHash.pm
    version: 0.99
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
version: 0.99
